/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.example.compiler.node;

import com.example.compiler.analysis.*;

@SuppressWarnings("nls")
public final class AWhileStmt extends PStmt
{
    private PPwhile _pwhile_;

    public AWhileStmt()
    {
        // Constructor
    }

    public AWhileStmt(
        @SuppressWarnings("hiding") PPwhile _pwhile_)
    {
        // Constructor
        setPwhile(_pwhile_);

    }

    @Override
    public Object clone()
    {
        return new AWhileStmt(
            cloneNode(this._pwhile_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhileStmt(this);
    }

    public PPwhile getPwhile()
    {
        return this._pwhile_;
    }

    public void setPwhile(PPwhile node)
    {
        if(this._pwhile_ != null)
        {
            this._pwhile_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pwhile_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pwhile_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pwhile_ == child)
        {
            this._pwhile_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pwhile_ == oldChild)
        {
            setPwhile((PPwhile) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
