/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.example.compiler.parser;

import com.example.compiler.lexer.*;
import com.example.compiler.node.*;
import com.example.compiler.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PStmtList node1 = (PStmtList) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AAstmtlist1StmtList */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAstmtlist2StmtList */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list, false);
            }
            break;
            case 2: /* reduce ANoopStmt */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce AAssignmentStmt */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list, false);
            }
            break;
            case 4: /* reduce AIfStmt */
            {
                ArrayList<Object> list = new4();
                push(goTo(1), list, false);
            }
            break;
            case 5: /* reduce ABlockStmt */
            {
                ArrayList<Object> list = new5();
                push(goTo(1), list, false);
            }
            break;
            case 6: /* reduce ANoElseIfStmt */
            {
                ArrayList<Object> list = new6();
                push(goTo(2), list, false);
            }
            break;
            case 7: /* reduce AWithElseIfStmt */
            {
                ArrayList<Object> list = new7();
                push(goTo(2), list, false);
            }
            break;
            case 8: /* reduce ANoopStmtWithElse */
            {
                ArrayList<Object> list = new8();
                push(goTo(3), list, false);
            }
            break;
            case 9: /* reduce AAssignmentStmtWithElse */
            {
                ArrayList<Object> list = new9();
                push(goTo(3), list, false);
            }
            break;
            case 10: /* reduce AIfStmtWithElse */
            {
                ArrayList<Object> list = new10();
                push(goTo(3), list, false);
            }
            break;
            case 11: /* reduce ABlockStmtWithElse */
            {
                ArrayList<Object> list = new11();
                push(goTo(3), list, false);
            }
            break;
            case 12: /* reduce AIfElseStmt */
            {
                ArrayList<Object> list = new12();
                push(goTo(4), list, false);
            }
            break;
            case 13: /* reduce ATerminal$Stmt */
            {
                ArrayList<Object> list = new13();
                push(goTo(5), list, true);
            }
            break;
            case 14: /* reduce ANonTerminal$Stmt */
            {
                ArrayList<Object> list = new14();
                push(goTo(5), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AAstmtlist1StmtList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PStmtList pstmtlistNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        }

        pstmtlistNode1 = new AStmtList(listNode2);
        }
	nodeList.add(pstmtlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAstmtlist2StmtList */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmtList pstmtlistNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }

        pstmtlistNode1 = new AStmtList(listNode3);
        }
	nodeList.add(pstmtlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce ANoopStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        TSemicolon tsemicolonNode2;
        tsemicolonNode2 = (TSemicolon)nodeArrayList1.get(0);

        pstmtNode1 = new ANoopStmt(tsemicolonNode2);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAssignmentStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TAssignOp tassignopNode3;
        TExp texpNode4;
        TSemicolon tsemicolonNode5;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        tassignopNode3 = (TAssignOp)nodeArrayList2.get(0);
        texpNode4 = (TExp)nodeArrayList3.get(0);
        tsemicolonNode5 = (TSemicolon)nodeArrayList4.get(0);

        pstmtNode1 = new AAssignmentStmt(tidentifierNode2, tassignopNode3, texpNode4, tsemicolonNode5);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AIfStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        PIfStmt pifstmtNode2;
        pifstmtNode2 = (PIfStmt)nodeArrayList1.get(0);

        pstmtNode1 = new AIfStmt(pifstmtNode2);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ABlockStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmt pstmtNode1;
        {
            // Block
        TLbrace tlbraceNode2;
        PStmtList pstmtlistNode3;
        TRbrace trbraceNode4;
        tlbraceNode2 = (TLbrace)nodeArrayList1.get(0);
        pstmtlistNode3 = (PStmtList)nodeArrayList2.get(0);
        trbraceNode4 = (TRbrace)nodeArrayList3.get(0);

        pstmtNode1 = new ABlockStmt(tlbraceNode2, pstmtlistNode3, trbraceNode4);
        }
	nodeList.add(pstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce ANoElseIfStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIfStmt pifstmtNode1;
        {
            // Block
        TIf tifNode2;
        TExp texpNode3;
        TThen tthenNode4;
        PStmt pstmtNode5;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        texpNode3 = (TExp)nodeArrayList2.get(0);
        tthenNode4 = (TThen)nodeArrayList3.get(0);
        pstmtNode5 = (PStmt)nodeArrayList4.get(0);

        pifstmtNode1 = new ANoElseIfStmt(tifNode2, texpNode3, tthenNode4, pstmtNode5);
        }
	nodeList.add(pifstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AWithElseIfStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIfStmt pifstmtNode1;
        {
            // Block
        TIf tifNode2;
        TExp texpNode3;
        TThen tthenNode4;
        PStmtWithElse pstmtwithelseNode5;
        TElse telseNode6;
        PStmt pstmtNode7;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        texpNode3 = (TExp)nodeArrayList2.get(0);
        tthenNode4 = (TThen)nodeArrayList3.get(0);
        pstmtwithelseNode5 = (PStmtWithElse)nodeArrayList4.get(0);
        telseNode6 = (TElse)nodeArrayList5.get(0);
        pstmtNode7 = (PStmt)nodeArrayList6.get(0);

        pifstmtNode1 = new AWithElseIfStmt(tifNode2, texpNode3, tthenNode4, pstmtwithelseNode5, telseNode6, pstmtNode7);
        }
	nodeList.add(pifstmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ANoopStmtWithElse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmtWithElse pstmtwithelseNode1;
        {
            // Block
        TSemicolon tsemicolonNode2;
        tsemicolonNode2 = (TSemicolon)nodeArrayList1.get(0);

        pstmtwithelseNode1 = new ANoopStmtWithElse(tsemicolonNode2);
        }
	nodeList.add(pstmtwithelseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AAssignmentStmtWithElse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmtWithElse pstmtwithelseNode1;
        {
            // Block
        TIdentifier tidentifierNode2;
        TAssignOp tassignopNode3;
        TExp texpNode4;
        TSemicolon tsemicolonNode5;
        tidentifierNode2 = (TIdentifier)nodeArrayList1.get(0);
        tassignopNode3 = (TAssignOp)nodeArrayList2.get(0);
        texpNode4 = (TExp)nodeArrayList3.get(0);
        tsemicolonNode5 = (TSemicolon)nodeArrayList4.get(0);

        pstmtwithelseNode1 = new AAssignmentStmtWithElse(tidentifierNode2, tassignopNode3, texpNode4, tsemicolonNode5);
        }
	nodeList.add(pstmtwithelseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AIfStmtWithElse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmtWithElse pstmtwithelseNode1;
        {
            // Block
        PIfElseStmt pifelsestmtNode2;
        pifelsestmtNode2 = (PIfElseStmt)nodeArrayList1.get(0);

        pstmtwithelseNode1 = new AIfStmtWithElse(pifelsestmtNode2);
        }
	nodeList.add(pstmtwithelseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce ABlockStmtWithElse */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PStmtWithElse pstmtwithelseNode1;
        {
            // Block
        TLbrace tlbraceNode2;
        PStmtList pstmtlistNode3;
        TRbrace trbraceNode4;
        tlbraceNode2 = (TLbrace)nodeArrayList1.get(0);
        pstmtlistNode3 = (PStmtList)nodeArrayList2.get(0);
        trbraceNode4 = (TRbrace)nodeArrayList3.get(0);

        pstmtwithelseNode1 = new ABlockStmtWithElse(tlbraceNode2, pstmtlistNode3, trbraceNode4);
        }
	nodeList.add(pstmtwithelseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AIfElseStmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PIfElseStmt pifelsestmtNode1;
        {
            // Block
        TIf tifNode2;
        TExp texpNode3;
        TThen tthenNode4;
        PStmtWithElse pstmtwithelseNode5;
        TElse telseNode6;
        PStmtWithElse pstmtwithelseNode7;
        tifNode2 = (TIf)nodeArrayList1.get(0);
        texpNode3 = (TExp)nodeArrayList2.get(0);
        tthenNode4 = (TThen)nodeArrayList3.get(0);
        pstmtwithelseNode5 = (PStmtWithElse)nodeArrayList4.get(0);
        telseNode6 = (TElse)nodeArrayList5.get(0);
        pstmtwithelseNode7 = (PStmtWithElse)nodeArrayList6.get(0);

        pifelsestmtNode1 = new AIfElseStmt(tifNode2, texpNode3, tthenNode4, pstmtwithelseNode5, telseNode6, pstmtwithelseNode7);
        }
	nodeList.add(pifelsestmtNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce ATerminal$Stmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PStmt pstmtNode1;
        pstmtNode1 = (PStmt)nodeArrayList1.get(0);
	if(pstmtNode1 != null)
	{
	  listNode2.add(pstmtNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce ANonTerminal$Stmt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PStmt pstmtNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pstmtNode2 = (PStmt)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pstmtNode2 != null)
	{
	  listNode3.add(pstmtNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {1, SHIFT, 1}, {4, SHIFT, 2}, {6, SHIFT, 3}, {7, SHIFT, 4}, },
			{{-1, ERROR, 1}, {0, SHIFT, 9}, },
			{{-1, REDUCE, 0}, {1, SHIFT, 1}, {4, SHIFT, 2}, {6, SHIFT, 3}, {7, SHIFT, 4}, },
			{{-1, REDUCE, 2}, },
			{{-1, ERROR, 4}, {8, SHIFT, 11}, },
			{{-1, ERROR, 5}, {9, ACCEPT, -1}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 1}, {1, SHIFT, 1}, {4, SHIFT, 2}, {6, SHIFT, 3}, {7, SHIFT, 4}, },
			{{-1, ERROR, 9}, {2, SHIFT, 13}, },
			{{-1, ERROR, 10}, {5, SHIFT, 14}, },
			{{-1, ERROR, 11}, {0, SHIFT, 15}, },
			{{-1, REDUCE, 14}, },
			{{-1, ERROR, 13}, {1, SHIFT, 16}, {4, SHIFT, 17}, {6, SHIFT, 18}, {7, SHIFT, 19}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 15}, {6, SHIFT, 23}, },
			{{-1, ERROR, 16}, {0, SHIFT, 24}, },
			{{-1, REDUCE, 0}, {1, SHIFT, 1}, {4, SHIFT, 2}, {6, SHIFT, 3}, {7, SHIFT, 4}, },
			{{-1, REDUCE, 2}, {3, REDUCE, 8}, },
			{{-1, ERROR, 19}, {8, SHIFT, 26}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 21}, {3, SHIFT, 27}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 3}, },
			{{-1, ERROR, 24}, {2, SHIFT, 28}, },
			{{-1, ERROR, 25}, {5, SHIFT, 29}, },
			{{-1, ERROR, 26}, {0, SHIFT, 30}, },
			{{-1, ERROR, 27}, {1, SHIFT, 1}, {4, SHIFT, 2}, {6, SHIFT, 3}, {7, SHIFT, 4}, },
			{{-1, ERROR, 28}, {1, SHIFT, 16}, {4, SHIFT, 17}, {6, SHIFT, 18}, {7, SHIFT, 19}, },
			{{-1, REDUCE, 5}, {3, REDUCE, 11}, },
			{{-1, ERROR, 30}, {6, SHIFT, 33}, },
			{{-1, REDUCE, 7}, },
			{{-1, ERROR, 32}, {3, SHIFT, 34}, },
			{{-1, REDUCE, 3}, {3, REDUCE, 9}, },
			{{-1, ERROR, 34}, {1, SHIFT, 16}, {4, SHIFT, 17}, {6, SHIFT, 18}, {7, SHIFT, 19}, },
			{{-1, REDUCE, 12}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 5}, {2, 10}, {17, 25}, },
			{{-1, 6}, {8, 12}, {13, 20}, {27, 31}, {28, 20}, {34, 31}, },
			{{-1, 7}, },
			{{-1, 21}, {28, 32}, {34, 35}, },
			{{-1, 22}, },
			{{-1, 8}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'if', '{', ';', identifier, EOF",
			"expecting: 'EXP'",
			"expecting: 'if', '{', '}', ';', identifier",
			"expecting: 'if', '{', '}', ';', identifier, EOF",
			"expecting: '<-'",
			"expecting: EOF",
			"expecting: 'then'",
			"expecting: '}'",
			"expecting: 'if', '{', ';', identifier",
			"expecting: ';'",
			"expecting: 'if', 'else', '{', '}', ';', identifier, EOF",
			"expecting: 'else'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 3, 4, 5, 3, 3, 3, 6, 7, 1, 3, 8, 3, 9, 1, 2, 10, 4, 3, 11, 11, 3, 6, 7, 1, 8, 8, 10, 9, 3, 11, 10, 8, 11, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
